import random 
import time

rule1 = "1.) You select a difficulty, a calculation is generated by the computer, and you have to answer it in the correct amount of time."
rule2 = "2.) If you answer the question in the correct amount of time, you have beaten the computer, and asked if you want to play again."
rule3 = "3.) If you answer the question incorrectly, you haven't beaten the computer, the answer is printed and you are asked if you want to play again."
rule4 = "4.) If you chose to play again, the while loop will reset."
rule5 = "5.) If you don't want to play again, the loop is ended and the program is exited."

menu = True 

operators = ["-", "+"]

def countdown(s):
    while s:
        mins, secs = divmod(s, 60)
        timer = '{:02d}:{:02d}'.format(mins, secs)
        print(timer, end="\r")
        time.sleep(1)
        s -= 1

print("would you like to play a game? yes or no? ")
gameInput = input()
if gameInput == "yes":
    while menu:
        rules = f"{rule1}\n{rule2}\n{rule3}\n{rule4}\n{rule5}"
        print(rules)
        print("the computer will now think of a caluculation: ")
        number1 = random.randint(1,100) 
        number2 = random.randint(1,100)
        operator = random.choice(operators)
        if operator == "+":
            answer = number1+number2
        elif operator == "-":
            answer = number1-number2 
        calculation = f"Calculation: {number1} {operator} {number2}"
        print("are you ready to work out the calculation? yes or no? ")
        workoutInput = str(input())
        if workoutInput == "yes":
            difficultyInput = input("what would you like your difficulty to be? easy, medium, or hard? ")
            print(calculation)
            if difficultyInput == "easy":
                s = 9 
                workoutTime = countdown(s)  
            elif difficultyInput == "medium":
                s = 7 
                workoutTime = countdown(s)
            elif difficultyInput == "hard":
                s = 5
                workoutTime = countdown(s)
            print("what is your answer? ")
            useranswer = int(input()) 
            if useranswer == answer:
                print("correct! well done!")
            else: 
                print(f"incorrect! the answer was: {answer}")
            print("would you like to play again? yes or no? ")
            againInput = str(input())
            if againInput == "no":
                print("exitting program!")
                menu = False
        else:
            print("exiting program!")
            menu = False 
else:
    print("exiting program!")